### ISSUE TITLE
Potential Bug

### ISSUE THREAD

**Issue by OneSharpAce** [InfinityRaider/Boatifull#11]
So my chest boats are sitting strangely low in the water. I have been able to reproduce this on all versions of your mod without any other mods being included. I say potentially a bug because viewing screenshots of other they don't appear to be having this issue.

http://i.imgur.com/Fy7xZUr.png

**Comment by InfinityRaider** [comment]
thats just because the hitbox of the chest boats is bigger, ive noticed it myself, i dont rly mind it cause it looks like the heavily loaded boat is deeper in the water.

**Comment by OneSharpAce** [comment]
Ok, thank you for a quick reply. Just wanted to make sure it wasn't a bug. My thoughts were the same. It looks like it is weighted down because of the chest weight.
