### ISSUE TITLE
[feature request] Update to 1.11.2

### ISSUE THREAD

**Issue by orionSquared** [InfinityRaider/Boatifull#14]
Good afternoon! Your mod looks absolutely fantastic and I'd LOVE to add it to my modpack. Sadly, my pack is for 1.11.2. Any chance you're working on a port to 1.11.2?

I'd greatly appreciate it!

**Comment by InfinityRaider** [comment]
@SkySom

**Comment by InfinityRaider** [comment]
1.11.2 build is on CF
