### ISSUE TITLE
Option to remove the tooltips and possibly add a tooltip for the boat

### ISSUE THREAD

**Issue by jurplel** [InfinityRaider/Boatifull#5]

**Comment by InfinityRaider** [comment]
whut?

**Comment by jurplel** [comment]
I'd like it if you added a config option to remove the tooltips on the lead and chest items, and possibly one to add a tooltip to the boats themselves.

**Comment by InfinityRaider** [comment]
I guess I could

**Comment by jurplel** [comment]
Thank you
