### ISSUE TITLE
Lead Duping

### ISSUE THREAD

**Issue by Ravin890** [InfinityRaider/Boatifull#6]
If you try to attach a chest boat with a lead to another boat, the leads don't attach and are doubling for some reason. (if you are holding more than 1 in your hand it will add the original amount to current amount. So if you are holding 1 there will be no issue but if you are holding 2 then you will have 3 after picking up lead and so on)
Also the chest boat won't connect to the boat ahead of it.

*Using forge 2115
boatiful 0.2
InfinityLib 0.2
Lantern 0.2

**Comment by InfinityRaider** [comment]
Tx for the report, I'll look into it

**Comment by InfinityRaider** [comment]
Does this also happen without Lantern?

**Comment by Ravin890** [comment]
Just tested and it also happens without lantern

*Also just tested with new lantern version and lib but same issue still occurs.

**Comment by InfinityRaider** [comment]
Ye I did not release a new Boatifull update yet. I'm just asking to see if i need to add lantern to my boatifull dev env or not.

**Comment by Ravin890** [comment]
I guessed as much which was why I also decided to test if the current version fixed it or not somehow or another as well.

**Comment by jonqrandom** [comment]
i can reproduce this using only boatifull 0.2 and InfinityLib 0.2 mods, on java 8 update 111, with forge 2099 and 2117. the duping occurs, and a boat with chest can lead an empty boat, but not vice versa.

i also tried adding Storage Boats 1.0 to test with. 
with boatifull 0.1 the Storage Boats chestboat can be set to lead and follow, with 0.2 it can do neither.

also, thank you for a great mod, i know it's "small" but it's one of those "should be vanilla" things :)

**Comment by InfinityRaider** [comment]
Ok, so something else went wrong between 0.1 and 0.2, narrows my search range down abit. 
Thanks for the info.

**Comment by jonqrandom** [comment]
you're welcome, i hope it was helpful :)

**Comment by InfinityRaider** [comment]
Ok I figured it out, it was a bug introduced with my new capability system in InfinityLib, fix is up, but I can't release yet because I have another new system in InfinityLib which needs more bugtesting.

InfinityLib commit with the fix: https://github.com/InfinityRaider/InfinityLib/commit/73d940199c584c9ab85bd5e0e5bb691f727e9562
