### ISSUE TITLE
[feature request] chest options

### ISSUE THREAD

**Issue by jonqrandom** [InfinityRaider/Boatifull#7]
seeing as currently, boats can have two riders, please will you consider the following two enhancements?

placing the chest at the end of the boat you're looking at. this would hopefully allow for a rider to still control the (unlinked or lead) boat if the chest is placed at the back, or for a single passenger or lantern to be on the boat wherever the chest is.

it would also potentially allow for a boat-with-double-chest, which is the other enhancement buzzing around my head.

if you don't like the ideas, then nonetheless thank you for taking the time to read this, and and thanks again for a great mod :)

**Comment by InfinityRaider** [comment]
I have considered this, but have decided not to do this (chest + rider and double chest).

Boats should have a limited buoyancy, you don't want to overload your boats to the point they sink.
Also the chest with rider defeats the purpose of the boat linking.

Thanks for the suggestions though.
